// Static sample data for feedback aggregator
const sampleFeedback = [
    {
        id: 1,
        source: 'github',
        sourceId: 'gh-001',
        title: 'Add dark mode support to the dashboard',
        content: 'The dashboard is great but it would be amazing to have dark mode support. Working late at night with the bright white interface is quite straining on the eyes. Many modern applications offer this feature and it would greatly improve the user experience for those of us who prefer darker themes.',
        author: 'Sarah Chen',
        authorEmail: 'sarah.chen@example.com',
        url: 'https://github.com/company/repo/issues/123',
        createdAt: '2024-01-20T10:30:00Z',
        sentiment: 'positive',
        sentimentScore: 0.8,
        urgency: 'medium',
        urgencyScore: 0.6,
        themes: ['UI/UX', 'Features'],
        keywords: ['dark mode', 'dashboard', 'user experience', 'interface'],
        summary: 'User requests dark mode support for better night-time usability.'
    },
    {
        id: 2,
        source: 'discord',
        sourceId: 'disc-001',
        title: 'Performance issues with large datasets',
        content: 'Hey team, I\'ve been experiencing significant performance degradation when working with datasets larger than 10,000 records. The dashboard becomes unresponsive and sometimes crashes. This is affecting our team\'s productivity as we need to analyze large customer datasets regularly.',
        author: 'Mike Johnson',
        authorEmail: 'mike.j@techcorp.com',
        url: 'https://discord.com/channels/123/456/789',
        createdAt: '2024-01-19T14:22:00Z',
        sentiment: 'negative',
        sentimentScore: -0.7,
        urgency: 'high',
        urgencyScore: 0.8,
        themes: ['Performance', 'Bugs'],
        keywords: ['performance', 'crashes', 'large datasets', 'unresponsive'],
        summary: 'Critical performance issues with large datasets causing crashes.'
    },
    {
        id: 3,
        source: 'twitter',
        sourceId: 'tw-001',
        title: 'Love the new analytics features!',
        content: 'Just started using the new analytics dashboard and I\'m blown away! The sentiment analysis and theme extraction features are incredibly helpful for our product team. Great work! 🎉',
        author: 'Emily Rodriguez',
        authorEmail: 'emily.r@startup.io',
        url: 'https://twitter.com/emilyrod/status/123456789',
        createdAt: '2024-01-19T09:15:00Z',
        sentiment: 'positive',
        sentimentScore: 0.9,
        urgency: 'low',
        urgencyScore: 0.2,
        themes: ['Features', 'Praise'],
        keywords: ['analytics', 'sentiment analysis', 'theme extraction', 'great work'],
        summary: 'Positive feedback on new analytics features.'
    },
    {
        id: 4,
        source: 'email',
        sourceId: 'email-001',
        title: 'Integration with Slack not working',
        content: 'We\'ve been trying to set up the Slack integration for the past week but it keeps failing. The webhook configuration seems correct but we\'re not receiving any notifications in our Slack channel. This is blocking our team\'s workflow as we rely on Slack for all internal communications.',
        author: 'David Kim',
        authorEmail: 'david.kim@enterprise.com',
        url: '',
        createdAt: '2024-01-18T16:45:00Z',
        sentiment: 'negative',
        sentimentScore: -0.6,
        urgency: 'critical',
        urgencyScore: 0.9,
        themes: ['Integration', 'Bugs'],
        keywords: ['slack integration', 'webhook', 'notifications', 'failing'],
        summary: 'Slack integration failure blocking team communications.'
    },
    {
        id: 5,
        source: 'support',
        sourceId: 'sup-001',
        title: 'Documentation needs more examples',
        content: 'The API documentation is comprehensive but lacks practical examples. Our developers are struggling to implement certain features because the use cases aren\'t clear. Adding more code examples and real-world scenarios would be incredibly helpful.',
        author: 'Lisa Thompson',
        authorEmail: 'lisa.t@devteam.com',
        url: 'https://support.company.com/tickets/456',
        createdAt: '2024-01-18T11:30:00Z',
        sentiment: 'neutral',
        sentimentScore: -0.1,
        urgency: 'medium',
        urgencyScore: 0.5,
        themes: ['Documentation'],
        keywords: ['documentation', 'examples', 'api', 'developers'],
        summary: 'Request for more practical examples in API documentation.'
    },
    {
        id: 6,
        source: 'github',
        sourceId: 'gh-002',
        title: 'Feature request: Export to PDF reports',
        content: 'It would be great to have the ability to export analytics reports as PDF files. Our management team prefers PDF format for presentations and sharing with stakeholders. Currently we have to manually create PDFs from screenshots which is time-consuming.',
        author: 'Robert Chang',
        authorEmail: 'robert.chang@corp.com',
        url: 'https://github.com/company/repo/issues/124',
        createdAt: '2024-01-17T13:20:00Z',
        sentiment: 'positive',
        sentimentScore: 0.3,
        urgency: 'medium',
        urgencyScore: 0.4,
        themes: ['Features', 'Export'],
        keywords: ['pdf export', 'reports', 'presentations', 'stakeholders'],
        summary: 'Feature request for PDF export functionality.'
    },
    {
        id: 7,
        source: 'discord',
        sourceId: 'disc-002',
        title: 'Mobile app would be amazing!',
        content: 'Have you considered creating a mobile app? I\'d love to check feedback analytics on the go. A mobile app would make it much easier to stay updated while traveling or away from the desk.',
        author: 'Amanda Foster',
        authorEmail: 'amanda.f@mobile.com',
        url: 'https://discord.com/channels/123/456/790',
        createdAt: '2024-01-17T08:45:00Z',
        sentiment: 'positive',
        sentimentScore: 0.7,
        urgency: 'low',
        urgencyScore: 0.3,
        themes: ['Features', 'Mobile'],
        keywords: ['mobile app', 'on the go', 'traveling', 'convenience'],
        summary: 'Suggestion for mobile app development.'
    },
    {
        id: 8,
        source: 'twitter',
        sourceId: 'tw-002',
        title: 'Customer service response time is excellent',
        content: 'Shoutout to the support team for the incredibly fast response times! Submitted a ticket yesterday and got a comprehensive solution within hours. This level of service is rare these days. 👏',
        author: 'James Wilson',
        authorEmail: 'james.w@customer.com',
        url: 'https://twitter.com/jwilson/status/123456790',
        createdAt: '2024-01-16T15:30:00Z',
        sentiment: 'positive',
        sentimentScore: 0.9,
        urgency: 'low',
        urgencyScore: 0.1,
        themes: ['Praise', 'Support'],
        keywords: ['customer service', 'response time', 'support team', 'fast'],
        summary: 'Praise for excellent customer service response times.'
    },
    {
        id: 9,
        source: 'email',
        sourceId: 'email-002',
        title: 'Security concerns about data storage',
        content: 'We are concerned about how our customer feedback data is stored and processed. Can you provide more information about your security measures, encryption standards, and compliance with GDPR and other data protection regulations?',
        author: 'Security Team',
        authorEmail: 'security@bank.com',
        url: '',
        createdAt: '2024-01-16T10:15:00Z',
        sentiment: 'negative',
        sentimentScore: -0.4,
        urgency: 'critical',
        urgencyScore: 0.9,
        themes: ['Security', 'Compliance'],
        keywords: ['security', 'data storage', 'encryption', 'GDPR', 'compliance'],
        summary: 'Security and compliance concerns about data handling.'
    },
    {
        id: 10,
        source: 'support',
        sourceId: 'sup-002',
        title: 'Pricing is too expensive for small teams',
        content: 'The pricing structure makes it difficult for small startups and indie developers to justify the cost. Consider introducing a tiered pricing model or a free tier with limited features to make it more accessible to smaller teams.',
        author: 'Alex Martinez',
        authorEmail: 'alex.m@startup.io',
        url: 'https://support.company.com/tickets/457',
        createdAt: '2024-01-15T14:20:00Z',
        sentiment: 'negative',
        sentimentScore: -0.5,
        urgency: 'medium',
        urgencyScore: 0.6,
        themes: ['Pricing'],
        keywords: ['pricing', 'expensive', 'small teams', 'startups', 'free tier'],
        summary: 'Feedback about pricing being too expensive for small teams.'
    },
    {
        id: 11,
        source: 'github',
        sourceId: 'gh-003',
        title: 'Bug: Duplicate entries in data export',
        content: 'When exporting data to CSV, I\'m noticing duplicate entries for some feedback items. This is causing issues when we try to import the data into our analytics tools. The duplicates seem to appear randomly and affect about 10% of the entries.',
        author: 'Chris Lee',
        authorEmail: 'chris.lee@analytics.com',
        url: 'https://github.com/company/repo/issues/125',
        createdAt: '2024-01-15T09:30:00Z',
        sentiment: 'negative',
        sentimentScore: -0.6,
        urgency: 'high',
        urgencyScore: 0.7,
        themes: ['Bugs', 'Export'],
        keywords: ['duplicate entries', 'csv export', 'data export', 'analytics'],
        summary: 'Bug report about duplicate entries in CSV exports.'
    },
    {
        id: 12,
        source: 'discord',
        sourceId: 'disc-003',
        title: 'Love the real-time updates!',
        content: 'The real-time feedback updates are fantastic! We can see new customer feedback as soon as it comes in, which helps us respond much faster. This has significantly improved our customer response times.',
        author: 'Nina Patel',
        authorEmail: 'nina.p@retail.com',
        url: 'https://discord.com/channels/123/456/791',
        createdAt: '2024-01-14T12:45:00Z',
        sentiment: 'positive',
        sentimentScore: 0.8,
        urgency: 'low',
        urgencyScore: 0.2,
        themes: ['Praise', 'Features'],
        keywords: ['real-time updates', 'customer feedback', 'response times'],
        summary: 'Positive feedback on real-time update feature.'
    },
    {
        id: 13,
        source: 'twitter',
        sourceId: 'tw-003',
        title: 'Integration with JIRA would be perfect',
        content: 'Our development team uses JIRA for project management. Integration between your feedback system and JIRA would streamline our workflow tremendously. We could automatically create tickets from high-priority feedback.',
        author: 'Tom Anderson',
        authorEmail: 'tom.a@devtools.com',
        url: 'https://twitter.com/tomanderson/status/123456791',
        createdAt: '2024-01-14T16:10:00Z',
        sentiment: 'positive',
        sentimentScore: 0.4,
        urgency: 'medium',
        urgencyScore: 0.5,
        themes: ['Integration', 'Features'],
        keywords: ['jira integration', 'project management', 'workflow', 'tickets'],
        summary: 'Feature request for JIRA integration.'
    },
    {
        id: 14,
        source: 'email',
        sourceId: 'email-003',
        title: 'Thank you for the excellent onboarding',
        content: 'I wanted to personally thank you for the smooth onboarding process. The guided tutorials and documentation made it incredibly easy to get started. Our team was up and running within hours of signing up.',
        author: 'Rachel Green',
        authorEmail: 'rachel.g@newco.com',
        url: '',
        createdAt: '2024-01-13T11:20:00Z',
        sentiment: 'positive',
        sentimentScore: 0.9,
        urgency: 'low',
        urgencyScore: 0.1,
        themes: ['Praise', 'Documentation'],
        keywords: ['onboarding', 'tutorials', 'documentation', 'easy to start'],
        summary: 'Positive feedback on smooth onboarding experience.'
    },
    {
        id: 15,
        source: 'support',
        sourceId: 'sup-003',
        title: 'API rate limiting too restrictive',
        content: 'The current API rate limiting of 100 requests per hour is too restrictive for our use case. We need to sync large amounts of feedback data and the current limits are causing delays in our data pipeline.',
        author: 'API Team',
        authorEmail: 'api@enterprise.com',
        url: 'https://support.company.com/tickets/458',
        createdAt: '2024-01-13T13:45:00Z',
        sentiment: 'negative',
        sentimentScore: -0.3,
        urgency: 'high',
        urgencyScore: 0.7,
        themes: ['Integration', 'Performance'],
        keywords: ['api rate limiting', 'requests per hour', 'data sync', 'delays'],
        summary: 'API rate limiting is too restrictive for large data syncs.'
    }
];

// Theme definitions with colors
const themes = [
    { name: 'UI/UX', color: '#4ecdc4', description: 'User interface and experience feedback' },
    { name: 'Performance', color: '#ff6b6b', description: 'System performance and speed issues' },
    { name: 'Features', color: '#45b7d1', description: 'Feature requests and functionality' },
    { name: 'Bugs', color: '#f7b731', description: 'Bug reports and issues' },
    { name: 'Documentation', color: '#5f27cd', description: 'Documentation and help content' },
    { name: 'Pricing', color: '#00d2d3', description: 'Pricing and billing feedback' },
    { name: 'Security', color: '#ee5a24', description: 'Security concerns and suggestions' },
    { name: 'Integration', color: '#a55eea', description: 'Third-party integrations' },
    { name: 'Praise', color: '#26de81', description: 'Positive feedback and compliments' },
    { name: 'Support', color: '#2bcbba', description: 'Customer support experiences' },
    { name: 'Compliance', color: '#fd79a8', description: 'Regulatory compliance issues' },
    { name: 'Export', color: '#6c5ce7', description: 'Data export functionality' },
    { name: 'Mobile', color: '#00b894', description: 'Mobile app and responsive design' }
];

// Source configurations
const sources = [
    { name: 'github', icon: 'fab fa-github', color: '#333' },
    { name: 'discord', icon: 'fab fa-discord', color: '#7289da' },
    { name: 'twitter', icon: 'fab fa-twitter', color: '#1da1f2' },
    { name: 'email', icon: 'fas fa-envelope', color: '#ea4335' },
    { name: 'support', icon: 'fas fa-life-ring', color: '#ff6b6b' }
];

// Sentiment and urgency configurations
const sentimentConfig = {
    positive: { color: '#26de81', icon: 'fas fa-smile', label: 'Positive' },
    neutral: { color: '#4299e1', icon: 'fas fa-meh', label: 'Neutral' },
    negative: { color: '#fc5c65', icon: 'fas fa-frown', label: 'Negative' }
};

const urgencyConfig = {
    critical: { color: '#eb3b5a', icon: 'fas fa-exclamation-circle', label: 'Critical' },
    high: { color: '#fa8231', icon: 'fas fa-exclamation-triangle', label: 'High' },
    medium: { color: '#f7b731', icon: 'fas fa-info-circle', label: 'Medium' },
    low: { color: '#26de81', icon: 'fas fa-check-circle', label: 'Low' }
};

// Export data for use in app.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        sampleFeedback,
        themes,
        sources,
        sentimentConfig,
        urgencyConfig
    };
}
